<?php

/*
|--------------------------------------------------------------------------
| Selected work
|--------------------------------------------------------------------------
|
| `plate` drives the generated visual — see App\Support\Plate. The seed is
| stable, so a project's artwork never changes between deploys.
|
| Every field below is optional except `slug`: App\Content\StaticContent
| normalises each record into a guaranteed shape before any view sees it,
| which is what allows the templates to render without testing for keys.
| A field added here is dropped unless the normaliser carries it through —
| that is deliberate, so the contract stays explicit rather than implied.
|
*/

return [
    [
        'id' => 1,
        'index' => '01',
        'slug' => 'kiln',
        'name' => 'Kiln',
        'title' => 'Kiln',
        'category' => 'Commerce platform',
        'year' => '2026',
        'statement' => 'Forty years of catalogue and no way to sell any of it.',
        'client' => 'Kiln Archive',
        'description' => 'A commerce platform that turned a dense ceramics archive into an intuitive, editorial buying experience.',
        'coverImage' => ['seed' => 1847, 'variant' => 'ink', 'ratio' => '16/9'],
        'clientLogo' => 'KILN / ARCHIVE',
        'challenge' => 'Thousands of objects were trapped in a catalogue designed for specialists, not collectors.',
        'solution' => 'We paired a flexible content model with expressive browsing tools and a fast, considered checkout.',
        'outcome' => 'A system that gives the archive room to breathe while making every object easier to find and buy.',
        'gallery' => [
            ['seed' => 1847, 'variant' => 'ink', 'ratio' => '4/3'],
            ['seed' => 1858, 'variant' => 'bone', 'ratio' => '16/10'],
        ],
        'services' => ['Strategy', 'Art direction', 'E-commerce', 'Infrastructure'],
        'stack' => ['Headless Shopify', 'Next.js', 'Sanity', 'Algolia'],
        'result' => ['value' => '+38%', 'label' => 'Revenue per session'],
        'featured' => true,
        'plate' => ['seed' => 1847, 'variant' => 'ink', 'ratio' => '4/3'],
        'alt' => 'Kiln — a dense stack of horizontal slabs in charcoal and oxide, reading as a cross-section through a ceramics archive.',
    ],
    [
        'id' => 2,
        'index' => '02',
        'slug' => 'meridian',
        'name' => 'Meridian',
        'title' => 'Meridian',
        'category' => 'Financial product',
        'year' => '2025',
        'statement' => 'Portfolio software for people who distrust portfolio software.',
        'client' => 'Meridian Capital',
        'description' => 'A financial product that trades dashboard noise for legible, confident decision-making.',
        'coverImage' => ['seed' => 2291, 'variant' => 'bone', 'ratio' => '16/9'],
        'clientLogo' => 'MERIDIAN',
        'challenge' => 'Experienced investors needed to understand risk and movement without deciphering another trading terminal.',
        'solution' => 'We designed a calm data language, clear portfolio narratives, and a flexible component system for the product team.',
        'outcome' => 'A more trusted product that made weekly review a habit instead of a chore.',
        'gallery' => [
            ['seed' => 2291, 'variant' => 'bone', 'ratio' => '3/4'],
            ['seed' => 2302, 'variant' => 'ink', 'ratio' => '16/10'],
        ],
        'services' => ['Product design', 'Research', 'Design system', 'Front-end'],
        'stack' => ['React', 'TypeScript', 'D3', 'Rust API'],
        'result' => ['value' => '4.1×', 'label' => 'Weekly active accounts'],
        'featured' => true,
        'plate' => ['seed' => 2291, 'variant' => 'bone', 'ratio' => '3/4'],
        'alt' => 'Meridian — pale layered bands offset against a ruled measurement grid, suggesting a portfolio broken into intervals.',
    ],
    [
        'id' => 3,
        'index' => '03',
        'slug' => 'aether',
        'name' => 'Aether',
        'title' => 'Aether',
        'category' => 'Brand &amp; web experience',
        'year' => '2025',
        'statement' => 'An atmospheric-sensing company that could not explain what it sensed.',
        'client' => 'Aether Systems',
        'description' => 'A new brand and web experience for a sensing platform making invisible conditions understandable.',
        'coverImage' => ['seed' => 733, 'variant' => 'signal', 'ratio' => '16/9'],
        'clientLogo' => 'AETHER / SYSTEMS',
        'challenge' => 'The technology was sophisticated, but its story was too technical to create momentum with new partners.',
        'solution' => 'We translated atmospheric data into a living visual language, then built a site that makes the science feel tangible.',
        'outcome' => 'A sharper market position and a richer sales conversation around what the platform makes possible.',
        'gallery' => [
            ['seed' => 733, 'variant' => 'signal', 'ratio' => '1/1'],
            ['seed' => 744, 'variant' => 'bone', 'ratio' => '16/10'],
        ],
        'services' => ['Brand', 'Web experience', 'WebGL', 'Motion'],
        'stack' => ['Three.js', 'GSAP', 'Astro', 'Cloudflare'],
        'result' => ['value' => '2.7×', 'label' => 'Qualified enquiries'],
        'featured' => false,
        'plate' => ['seed' => 733, 'variant' => 'signal', 'ratio' => '1/1'],
        'alt' => 'Aether — thin translucent strata drifting apart over a dark field, evoking layers of atmosphere under measurement.',
    ],
    [
        'id' => 4,
        'index' => '04',
        'slug' => 'northbound',
        'name' => 'Northbound',
        'title' => 'Northbound',
        'category' => 'Mobile experience',
        'year' => '2024',
        'statement' => 'Trail navigation for people who lose signal on purpose.',
        'client' => 'Northbound',
        'description' => 'An offline-first mobile experience built for people who head outside of coverage on purpose.',
        'coverImage' => ['seed' => 3608, 'variant' => 'ink', 'ratio' => '16/9'],
        'clientLogo' => 'NORTHBOUND',
        'challenge' => 'Critical route information had to stay clear, useful, and available when a connection disappeared.',
        'solution' => 'We designed a compact navigation system around offline maps, glanceable terrain context, and durable saved routes.',
        'outcome' => 'A focused companion that made explorers more confident long after the signal dropped.',
        'gallery' => [
            ['seed' => 3608, 'variant' => 'ink', 'ratio' => '16/9'],
            ['seed' => 3619, 'variant' => 'signal', 'ratio' => '4/3'],
        ],
        'services' => ['Product design', 'Mobile', 'Motion', 'Design system'],
        'stack' => ['React Native', 'MapLibre', 'SQLite', 'Expo'],
        'result' => ['value' => '61%', 'label' => 'Day-30 retention'],
        'featured' => false,
        'plate' => ['seed' => 3608, 'variant' => 'ink', 'ratio' => '16/9'],
        'alt' => 'Northbound — a ascending diagonal of narrow slabs across a dark field, reading as a route gaining elevation.',
    ],
    [
        'id' => 5,
        'index' => '05',
        'slug' => 'ledgerline',
        'name' => 'Ledgerline',
        'title' => 'Ledgerline',
        'category' => 'Business systems / ERP',
        'year' => '2026',
        'statement' => 'Three warehouses, one spreadsheet, and nobody who trusted the number in it.',
        'client' => 'Ledgerline Distribution',
        'description' => 'An Odoo ERP implementation that unified inventory, finance and field sales for a regional distributor across three warehouses.',
        'coverImage' => ['seed' => 6204, 'variant' => 'signal', 'ratio' => '16/9'],
        'clientLogo' => 'LEDGERLINE',
        'challenge' => 'Stock counts, pricing and commissions each lived in a different spreadsheet, reconciled by hand at month end — and rarely agreed with each other.',
        'solution' => 'We implemented Odoo across inventory, accounting and CRM, migrated four years of records, and automated the handoffs between warehouse, finance and the field sales team.',
        'outcome' => 'One system of record that closes the month in days, not weeks, and a sales team that can see live stock from a phone.',
        'gallery' => [
            ['seed' => 6204, 'variant' => 'signal', 'ratio' => '4/3'],
            ['seed' => 6231, 'variant' => 'ink', 'ratio' => '16/10'],
        ],
        'services' => ['Discovery', 'Odoo implementation', 'Data migration', 'Automation'],
        'stack' => ['Odoo 17', 'PostgreSQL', 'Python', 'Zapier'],
        'result' => ['value' => '6 days', 'label' => 'Faster month-end close'],
        'featured' => true,
        'plate' => ['seed' => 6204, 'variant' => 'signal', 'ratio' => '4/3'],
        'alt' => 'Ledgerline — interlocking rectilinear slabs in oxide and charcoal, reading as three separate ledgers resolving into one structure.',
    ],
];
